import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import ConditionalHeader from "@/components/layouts/conditional-header";
import Footer from "@/components/layouts/footer";
import PreviewLanding from "@/components/preview/preview-landing";
import { isPreviewMode } from "@/lib/app-mode";
const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify organizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", dmSans.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ConditionalHeader />
        <main className="flex-1">
          {/* In preview mode no route renders: every URL shows the walkthrough
              instead, so nothing in the app can talk to Spotify. */}
          {isPreviewMode ? <PreviewLanding /> : children}
        </main>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
